services:
  courses-api:
    image: courses-api:latest
    container_name: courses-api
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=8000
    ports:
      - 3530:8000
    networks:
      - csclub

networks:
  csclub:
    external: true
